import type { Meta, StoryObj } from "@storybook/react-vite";
import Leaderboard from "./Leaderboard";
import { Driver } from "../types/Driver";

const exampleDrivers: Driver[] = [
  {
    carId: 1,
    firstName: "Lewis",
    lastName: "Hamilton",
    position: 1,
    classPosition: 1,
    isCarOnTrack: true,
    iRating: 9000,
    iRatingChange: 25,
    carClassShortName: "GT3",
    iRacingLicString: "A",
    iRacingLicSubLevel: 3,
    isSelected: false,
  },
  {
    carId: 2,
    firstName: "Max",
    lastName: "Verstappen",
    position: 2,
    classPosition: 2,
    isCarOnTrack: true,
    iRating: 8700,
    iRatingChange: -10,
    carClassShortName: "GT3",
    iRacingLicString: "B",
    iRacingLicSubLevel: 2,
    isSelected: false,
  },
  {
    carId: 3,
    firstName: "Charles",
    lastName: "Leclerc",
    position: 3,
    classPosition: 3,
    isCarOnTrack: true,
    iRating: 8500,
    iRatingChange: 0,
    carClassShortName: "GT3",
    iRacingLicString: "C",
    iRacingLicSubLevel: 1,
    isSelected: false,
  },
  {
    carId: 4,
    firstName: "Lando",
    lastName: "Norris",
    position: 4,
    classPosition: 4,
    isCarOnTrack: true,
    iRating: 8000,
    iRatingChange: 12,
    carClassShortName: "GT3",
    iRacingLicString: "D",
    iRacingLicSubLevel: 0,
    isSelected: false,
  },
  {
    carId: 5,
    firstName: "Fernando",
    lastName: "Alonso",
    position: 5,
    classPosition: 5,
    isCarOnTrack: true,
    iRating: 7800,
    iRatingChange: -5,
    carClassShortName: "GT3",
    iRacingLicString: "R",
    iRacingLicSubLevel: 4,
    isSelected: false,
  },
  {
    carId: 6,
    firstName: "Sebastian",
    lastName: "Vettel",
    position: 6,
    classPosition: 6,
    isCarOnTrack: true,
    iRating: 7600,
    iRatingChange: 0,
    carClassShortName: "GT3",
    iRacingLicString: "A",
    iRacingLicSubLevel: 2,
    isSelected: false,
  },
  {
    carId: 12,
    firstName: "You",
    lastName: "Player",
    position: 7,
    classPosition: 7,
    isCarOnTrack: true,
    iRating: 7400,
    iRatingChange: 8,
    carClassShortName: "GT3",
    iRacingLicString: "B",
    iRacingLicSubLevel: 3,
    isSelected: false,
  },
  {
    carId: 8,
    firstName: "George",
    lastName: "Russell",
    position: 8,
    classPosition: 8,
    isCarOnTrack: true,
    iRating: 7200,
    iRatingChange: -3,
    carClassShortName: "GT3",
    iRacingLicString: "C",
    iRacingLicSubLevel: 1,
    isSelected: false,
  },
  {
    carId: 9,
    firstName: "Carlos",
    lastName: "Sainz",
    position: 9,
    classPosition: 9,
    isCarOnTrack: true,
    iRating: 7100,
    iRatingChange: 6,
    carClassShortName: "GT3",
    iRacingLicString: "D",
    iRacingLicSubLevel: 2,
    isSelected: false,
  },
  {
    carId: 10,
    firstName: "Valtteri",
    lastName: "Bottas",
    position: 10,
    classPosition: 10,
    isCarOnTrack: true,
    iRating: 7000,
    iRatingChange: -2,
    carClassShortName: "GT3",
    iRacingLicString: "A",
    iRacingLicSubLevel: 1,
    isSelected: false,
  },
  {
    carId: 11,
    firstName: "Sergio",
    lastName: "Perez",
    position: 11,
    classPosition: 11,
    isCarOnTrack: true,
    iRating: 6900,
    iRatingChange: 4,
    carClassShortName: "GT3",
    iRacingLicString: "B",
    iRacingLicSubLevel: 0,
    isSelected: false,
  },
  {
    carId: 13,
    firstName: "Esteban",
    lastName: "Ocon",
    position: 12,
    classPosition: 12,
    isCarOnTrack: true,
    iRating: 6800,
    iRatingChange: 1,
    carClassShortName: "GT3",
    iRacingLicString: "C",
    iRacingLicSubLevel: 2,
    isSelected: false,
  },
  {
    carId: 14,
    firstName: "Pierre",
    lastName: "Gasly",
    position: 13,
    classPosition: 13,
    isCarOnTrack: true,
    iRating: 6700,
    iRatingChange: -7,
    carClassShortName: "GT3",
    iRacingLicString: "D",
    iRacingLicSubLevel: 1,
    isSelected: true,
  },
  {
    carId: 15,
    firstName: "Kevin",
    lastName: "Magnussen",
    position: 14,
    classPosition: 14,
    isCarOnTrack: true,
    iRating: 6600,
    iRatingChange: 3,
    carClassShortName: "GT3",
    iRacingLicString: "R",
    iRacingLicSubLevel: 3,
    isSelected: false,
  },
  {
    carId: 16,
    firstName: "Lance",
    lastName: "Stroll",
    position: 15,
    classPosition: 15,
    isCarOnTrack: true,
    iRating: 6500,
    iRatingChange: 0,
    carClassShortName: "GT3",
    iRacingLicString: "A",
    iRacingLicSubLevel: 0,
    isSelected: false,
  },
  {
    carId: 17,
    firstName: "Yuki",
    lastName: "Tsunoda",
    position: 16,
    classPosition: 16,
    isCarOnTrack: true,
    iRating: 6400,
    iRatingChange: 2,
    carClassShortName: "GT3",
    iRacingLicString: "B",
    iRacingLicSubLevel: 1,
    isSelected: false,
  },
  {
    carId: 18,
    firstName: "Zhou",
    lastName: "Guanyu",
    position: 17,
    classPosition: 17,
    isCarOnTrack: true,
    iRating: 6300,
    iRatingChange: -4,
    carClassShortName: "GT3",
    iRacingLicString: "C",
    iRacingLicSubLevel: 0,
    isSelected: false,
  },
  {
    carId: 19,
    firstName: "Alexander",
    lastName: "Albon",
    position: 18,
    classPosition: 18,
    isCarOnTrack: true,
    iRating: 6200,
    iRatingChange: 5,
    carClassShortName: "GT3",
    iRacingLicString: "D",
    iRacingLicSubLevel: 3,
    isSelected: false,
  },
];

const meta: Meta<typeof Leaderboard> = {
  title: "Components/Leaderboard",
  component: Leaderboard,
  tags: ["autodocs"],
  argTypes: {
    backgroundOpacity: {
      control: { type: "range", min: 0, max: 1, step: 0.05 },
    },
    fontSize: { control: "object" },
  },
};

export default meta;

type Story = StoryObj<typeof Leaderboard>;

export const Default: Story = {
  args: {
    drivers: exampleDrivers,
  },
};

export const CustomFontSize: Story = {
  args: {
    drivers: exampleDrivers,
    fontSize: {
      position: "20px",
      driverName: "18px",
      safetyRating: "16px",
      iRating: "16px",
      iRatingChange: "15px",
    },
  },
};

export const LowOpacity: Story = {
  args: {
    drivers: exampleDrivers,
    backgroundOpacity: 0.2,
  },
};

export const CurrentDriverNearTop: Story = {
  args: {
    drivers: exampleDrivers,
  },
};

export const FewerDrivers: Story = {
  args: {
    drivers: exampleDrivers.slice(0, 5),
  },
};
