import type { Meta, StoryObj } from "@storybook/react-vite";
import { Driver } from "../types/Driver";
import Standings from "./standings";
import { SessionRacing } from "../types/Session";

const exampleDrivers: Driver[] = [
  // GT3 class (first 6 drivers)
  {
    carIdx: 1,
    firstName: "Lewis",
    lastName: "Hamilton",
    position: 1,
    classPosition: 1,
    isCarOnTrack: true,
    iRating: 9000,
    iRatingChange: 25,
    carClassShortName: "GT3",
    carClassId: 101,
    iRacingLicString: "A",
    iRacingLicSubLevel: 3,
    isSelected: false,
  },
  {
    carIdx: 2,
    firstName: "Max",
    lastName: "Verstappen",
    position: 2,
    classPosition: 2,
    isCarOnTrack: true,
    iRating: 8700,
    iRatingChange: -10,
    carClassShortName: "GT3",
    carClassId: 101,
    iRacingLicString: "B",
    iRacingLicSubLevel: 2,
    isSelected: false,
  },
  {
    carIdx: 3,
    firstName: "Charles",
    lastName: "Leclerc",
    position: 3,
    classPosition: 3,
    isCarOnTrack: true,
    iRating: 8500,
    iRatingChange: 0,
    carClassShortName: "GT3",
    carClassId: 101,
    iRacingLicString: "C",
    iRacingLicSubLevel: 1,
    isSelected: false,
  },
  {
    carIdx: 4,
    firstName: "Lando",
    lastName: "Norris",
    position: 4,
    classPosition: 4,
    isCarOnTrack: true,
    iRating: 8000,
    iRatingChange: 12,
    carClassShortName: "GT3",
    carClassId: 101,
    iRacingLicString: "D",
    iRacingLicSubLevel: 0,
    isSelected: false,
  },
  {
    carIdx: 5,
    firstName: "Fernando",
    lastName: "Alonso",
    position: 5,
    classPosition: 5,
    isCarOnTrack: true,
    iRating: 7800,
    iRatingChange: -5,
    carClassShortName: "GT3",
    carClassId: 101,
    iRacingLicString: "R",
    iRacingLicSubLevel: 4,
    isSelected: false,
  },
  {
    carIdx: 6,
    firstName: "Sebastian",
    lastName: "Vettel",
    position: 6,
    classPosition: 6,
    isCarOnTrack: true,
    iRating: 7600,
    iRatingChange: 0,
    carClassShortName: "GT3",
    carClassId: 101,
    iRacingLicString: "A",
    iRacingLicSubLevel: 2,
    isSelected: false,
  },

  // GT4 class (next 6 drivers)
  {
    carIdx: 12,
    firstName: "You",
    lastName: "Player",
    position: 7,
    classPosition: 1,
    isCarOnTrack: true,
    iRating: 7400,
    iRatingChange: 8,
    carClassShortName: "GT4",
    carClassId: 202,
    iRacingLicString: "B",
    iRacingLicSubLevel: 3,
    isSelected: false,
  },
  {
    carIdx: 8,
    firstName: "George",
    lastName: "Russell",
    position: 8,
    classPosition: 2,
    isCarOnTrack: true,
    iRating: 7200,
    iRatingChange: -3,
    carClassShortName: "GT4",
    carClassId: 202,
    iRacingLicString: "C",
    iRacingLicSubLevel: 1,
    isSelected: false,
  },
  {
    carIdx: 9,
    firstName: "Carlos",
    lastName: "Sainz",
    position: 9,
    classPosition: 3,
    isCarOnTrack: true,
    iRating: 7100,
    iRatingChange: 6,
    carClassShortName: "GT4",
    carClassId: 202,
    iRacingLicString: "D",
    iRacingLicSubLevel: 2,
    isSelected: false,
  },
  {
    carIdx: 10,
    firstName: "Valtteri",
    lastName: "Bottas",
    position: 10,
    classPosition: 4,
    isCarOnTrack: true,
    iRating: 7000,
    iRatingChange: -2,
    carClassShortName: "GT4",
    carClassId: 202,
    iRacingLicString: "A",
    iRacingLicSubLevel: 1,
    isSelected: false,
  },
  {
    carIdx: 11,
    firstName: "Sergio",
    lastName: "Perez",
    position: 11,
    classPosition: 5,
    isCarOnTrack: true,
    iRating: 6900,
    iRatingChange: 4,
    carClassShortName: "GT4",
    carClassId: 202,
    iRacingLicString: "B",
    iRacingLicSubLevel: 0,
    isSelected: false,
  },
  {
    carIdx: 13,
    firstName: "Esteban",
    lastName: "Ocon",
    position: 12,
    classPosition: 6,
    isCarOnTrack: true,
    iRating: 6800,
    iRatingChange: 1,
    carClassShortName: "GT4",
    carClassId: 202,
    iRacingLicString: "C",
    iRacingLicSubLevel: 2,
    isSelected: false,
  },

  // IMSA class (last 6 drivers)
  {
    carIdx: 14,
    firstName: "Pierre",
    lastName: "Gasly",
    position: 13,
    classPosition: 1,
    isCarOnTrack: true,
    iRating: 6700,
    iRatingChange: -7,
    carClassShortName: "IMSA",
    carClassId: 303,
    iRacingLicString: "D",
    iRacingLicSubLevel: 1,
    isSelected: true,
  },
  {
    carIdx: 15,
    firstName: "Kevin",
    lastName: "Magnussen",
    position: 14,
    classPosition: 2,
    isCarOnTrack: true,
    iRating: 6600,
    iRatingChange: 3,
    carClassShortName: "IMSA",
    carClassId: 303,
    iRacingLicString: "R",
    iRacingLicSubLevel: 3,
    isSelected: false,
  },
  {
    carIdx: 16,
    firstName: "Lance",
    lastName: "Stroll",
    position: 15,
    classPosition: 3,
    isCarOnTrack: true,
    iRating: 6500,
    iRatingChange: 0,
    carClassShortName: "IMSA",
    carClassId: 303,
    iRacingLicString: "A",
    iRacingLicSubLevel: 0,
    isSelected: false,
  },
  {
    carIdx: 17,
    firstName: "Yuki",
    lastName: "Tsunoda",
    position: 16,
    classPosition: 4,
    isCarOnTrack: true,
    iRating: 6400,
    iRatingChange: 2,
    carClassShortName: "IMSA",
    carClassId: 303,
    iRacingLicString: "B",
    iRacingLicSubLevel: 1,
    isSelected: false,
  },
  {
    carIdx: 18,
    firstName: "Zhou",
    lastName: "Guanyu",
    position: 17,
    classPosition: 5,
    isCarOnTrack: true,
    iRating: 6300,
    iRatingChange: -4,
    carClassShortName: "IMSA",
    carClassId: 303,
    iRacingLicString: "C",
    iRacingLicSubLevel: 0,
    isSelected: false,
  },
  {
    carIdx: 19,
    firstName: "Alexander",
    lastName: "Albon",
    position: 18,
    classPosition: 6,
    isCarOnTrack: true,
    iRating: 6200,
    iRatingChange: 5,
    carClassShortName: "IMSA",
    carClassId: 303,
    iRacingLicString: "D",
    iRacingLicSubLevel: 3,
    isSelected: false,
  },
];

const sessionExample: SessionRacing = {
  sessionCurrentTime: 465,
  sessionDuration: 1200,
  sessionType: "RACE",
};

const meta: Meta<typeof Standings> = {
  title: "Components/Standings",
  component: Standings,
  tags: ["autodocs"],
  argTypes: {
    // backgroundOpacity: {
    //   control: { type: "range", min: 0, max: 1, step: 0.05 },
    // },
    // fontSize: { control: "object" },
  },
};

export default meta;

type Story = StoryObj<typeof Standings>;

export const Default: Story = {
  args: {
    drivers: exampleDrivers,
    session: sessionExample,
  },
};

export const CustomFontSize: Story = {
  args: {
    drivers: exampleDrivers,
    session: sessionExample,
    // fontSize: {
    //   position: "20px",
    //   driverName: "18px",
    //   safetyRating: "16px",
    //   iRating: "16px",
    //   iRatingChange: "15px",
    // },
  },
};

export const LowOpacity: Story = {
  args: {
    drivers: exampleDrivers,
    session: sessionExample,
    // backgroundOpacity: 0.2,
  },
};

export const CurrentDriverNearTop: Story = {
  args: {
    drivers: exampleDrivers,
    session: sessionExample,
  },
};

export const FewerDrivers: Story = {
  args: {
    drivers: exampleDrivers.slice(0, 5),
    session: sessionExample,
  },
};
